version: '3.7'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=hvalfangst
      - POSTGRES_PASSWORD=Plankton240p
      - POSTGRES_DB=hval_db
    ports:
      - '5433:5432'